-- Migration: 0007_update_programs_from_doc_v2
-- Replaces old programs with the updated ones from RevisiProgramuntukWebsite_07072026.docx

DELETE FROM public.marungga_programs;

INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('PELITA PAUD', '2026 - 2029', 'Program PELITA PAUD berfokus pada penguatan ekosistem pendidikan anak usia dini di Kabupaten Kupang melalui peningkatan dukungan teknis, kebijakan, dan pendanaan dari pemerintah daerah serta pemerintah desa. Program ini memperkuat fungsi Pusat Kegiatan Gugus (PKG) PAUD sebagai komunitas belajar bagi pendidik dalam meningkatkan kualitas pembelajaran, kemitraan dengan orang tua, dan kapasitas advokasi yang didampingi oleh OPD terkait. Melalui program ini, kapasitas mentor PAUD dan fasilitator PKG diperkuat agar mampu melaksanakan pelatihan, pendampingan, dan pemantauan secara berkelanjutan. Program juga mendorong penerapan kurikulum PAUD yang berkualitas dan kontekstual dengan mengintegrasikan Pembelajaran Mendalam dan 7 KAIH, serta memperkuat keterlibatan orang tua dalam proses pembelajaran. Selain itu, PELITA PAUD mendorong hadirnya dukungan kebijakan dan alokasi anggaran desa untuk memastikan partisipasi aktif satuan PAUD dalam kegiatan PKG dan keberlanjutan peningkatan mutu layanan PAUD.', 'Rp 5.232.118.290', '/programs/v2_image3.png', 0);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Program Pengembangan Kurikulum Operasional Satuan PAUD', '2024 - 2025', 'Program KAPSUL PAUD mendukung mentor dan pendidik dari 24 PAUD percontohan di Kabupaten Kupang dalam menyusun Kurikulum Operasional Satuan Pendidikan (KOSP) PAUD yang berkualitas, kontekstual, dan sesuai dengan kebutuhan serta karakteristik lokal. Program ini juga mendorong penerapan KOSP secara efektif dalam proses pembelajaran di satuan PAUD, sehingga dapat meningkatkan kualitas layanan pendidikan anak usia dini yang lebih relevan, bermakna, dan berpusat pada kebutuhan anak.', 'Rp 994.569.600', '/programs/v2_image4.png', 1);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Supportive Supervision on Maternal Nutrition and Child Health and WIFA', '2023', 'Kegiatan ini bertujuan untuk memperkuat kualitas pelaksanaan program gizi ibu dan kesehatan anak serta program suplementasi tablet tambah darah mingguan bagi remaja putri melalui pendampingan, pemantauan, dan pembinaan kepada Puskesmas dan sekolah sasaran. Melalui supervisi suportif, diharapkan kapasitas petugas kesehatan dan pihak sekolah dalam mengelola program dapat meningkat sehingga cakupan dan kualitas layanan gizi bagi ibu, anak, dan remaja semakin optimal.', 'Rp. 340.304.000', '/placeholder.jpg', 2);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Training on Vitamin A Supplementation (VAS) Integrated Management', '2023', 'Program ini bertujuan untuk meningkatkan kapasitas petugas program gizi dan farmasi dalam pengelolaan program suplementasi Vitamin A secara terpadu, serta memperkuat sistem manajemen rantai pasok Kapsul Vitamin A guna menjamin ketersediaan dan distribusi yang efektif hingga tingkat layanan kesehatan.', 'Rp 665,677,000', '/placeholder.jpg', 3);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Dokumentasi Karya Para Maestro Kepercayaan dan Kebudayaan Jingitiu', '2023 - 2024', 'Kegiatan ini mencakup proses identifikasi dan penyusunan rencana dokumentasi, produksi 10 karya audio visual, serta penyusunan satu buku dokumentasi yang merekam pengetahuan, nilai, dan karya para maestro Kepercayaan dan Kebudayaan Jingitiu. Selain itu, dilakukan peluncuran hasil karya dokumentasi beserta website dokumentasi karya agung para maestro Kepercayaan dan Kebudayaan Jingitiu sebagai media pelestarian dan diseminasi pengetahuan budaya. Hasil dokumentasi juga disosialisasikan kepada Dinas Pendidikan serta kepala satuan pendidikan tingkat SD, SMP, dan SMA/SMK di Kabupaten Sabu Raijua untuk mendorong pemanfaatannya sebagai sumber pembelajaran dan penguatan pendidikan berbasis budaya lokal.', 'Rp 492.908.163', '/programs/v2_image1.png', 4);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Pengembangan ternak sapi', '2022 - 2026', 'merupakan program internal Marungga yang bertujuan mendukung keberlanjutan organisasi sekaligus memberdayakan anak muda di Kabupaten Kupang. Melalui program ini, Marungga menyediakan bibit sapi yang kemudian dipelihara dan dikembangkan. Setelah ternak dijual, hasil penjualan akan dibagikan berdasarkan kesepakatan yang telah dibangun bersama.', 'Rp 21.000.000 setiap kali pengadaan 3 ekor sapi', '/programs/v2_image7.png', 5);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Dukungan Proyek Lii Marapu (Kemendikbudristek RI)', '2022 - 2023', 'Melaksanakan kegiatan untuk mendukung proyek Lii Marapu yang didanai oleh Direktorat Kebudayaan & Masyarakat Adat, Kemendikbudristek RI pada tahun 2022-2023.', '', '/placeholder.jpg', 6);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Pelatihan Menulis secara online', '2021', 'Pelatihan menulis dilakukan sebagai upaya untuk memperkuat kemampuan peserta dalam menulis dimulai dari teknik menulis kreatif,  seperti menemukan ide tulisan dan mengembangkan alur cerita hingga menjadi tulisan yang menarik', 'Kegiatan ini tidak mengeluarkan biaya karena dilakukan secara online', '/programs/v2_image6.png', 7);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Respon Bencana kasus Seroja di Kabupaten dan Kota Kupang', '2021', 'Kegiatan ini berupa penggalangan dana kemanusiaan yang kemudian digunakan untuk memenuhi kebutuhan dasar masyarakat terdampak. Bantuan yang disalurkan meliputi paket sembako, obat-obatan, serta berbagai kebutuhan mendesak lainnya guna mendukung keberlangsungan hidup warga pada masa tanggap darurat. Selain bantuan material, tim juga memberikan dukungan psikososial awal bagi anak-anak yang terdampak bencana.', 'Rp. 35.025.000', '/programs/v2_image9.png', 8);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Peningkatan Kapasitas Kehidupan bagi Eks Pekerja migran', '2021', 'Bekerja sama dengan Sumba Integrated Development ( SID) dalam menyusun proposal dan memfasilitasi peningkatan kapasitas Kehidupan bagi Eks Pekerja migran di Kabupaten Sumba Barat dan Sumba Barat Daya Provinsi Nusa Tenggara Timur yang didanai oleh International Of Migration (IOM).', '', '/placeholder.jpg', 9);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Penyusunan Proposal Hibah VOICE', '2021', 'Bersama Sumba Integrated Development ( SID) Menyusun Proposal Hibah VOICE.', '', '/placeholder.jpg', 10);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Proyek BISA (Nutrisi)', '2021', 'Program ini bertujuan untuk mendukung peningkatan akses, ketersediaan, dan pemanfaatan intervensi gizi esensial bagi ibu, remaja putri, bayi, dan anak. Kegiatan difokuskan pada penguatan pelaksanaan suplementasi zat besi dan asam folat (IFA dan WIFA), distribusi Kapsul Vitamin A, pemberian Zinc dan Oralit (ORS), serta peningkatan kapasitas pelaksana program guna mendukung upaya pencegahan stunting dan perbaikan status gizi masyarakat.', 'Rp. 501.490.000', '/programs/v2_image8.png', 11);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Proyek Lii Marapu', '2021 - 2023', 'Program ini berfokus pada penguatan pengakuan, akses layanan, dan pemenuhan hak-hak Penghayat Kepercayaan Marapu melalui empat pilar utama. Pertama, penguatan kapasitas Badan Pengurus Marapu (BPM) di tingkat kabupaten sebagai wadah untuk memobilisasi sumber daya dan melakukan advokasi. Kedua, pemberdayaan lembaga adat di tingkat desa untuk memperkuat peran dalam mobilisasi sumber daya dan advokasi komunitas. Ketiga, pengembangan model layanan pendidikan kepercayaan di sekolah menengah atas (SMA) percontohan yang mendukung implementasi pendidikan Kepercayaan terhadap Tuhan Yang Maha Esa (Marapu). Keempat, penguatan dukungan kebijakan pemerintah daerah di tingkat kabupaten dan desa guna memperluas akses terhadap layanan sosial dan pendidikan bagi Penghayat Marapu serta memperkuat pengakuan mereka di tingkat daerah, provinsi, dan nasional.', 'Rp 2.989.419.500', '/programs/v2_image2.png', 12);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Pengembangan Diri bagi 20 orang Anak Muda di Kota Kupang', '2020', 'Merupakan program internal Marungga untuk membantu anak muda mengenali dan mengelola potensi diri melalui identifikasi bakat serta kemampuan yang dimiliki oleh setiap peserta. Peserta juga didampingi untuk menyusun rencana pengembangan diri yang sesuai dengan potensi, minat, dan tujuan yang ingin dicapai.', 'Rp 1.000.000', '/programs/v2_image5.png', 13);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Lokakarya Orientasi dan Peningkatan Kapasitas Program Suplementasi WIFA', '2020 - 2021', 'Kegiatan ini bertujuan meningkatkan pemahaman dan kapasitas tenaga kesehatan, pengelola program, serta pemangku kepentingan terkait dalam pelaksanaan program WIFA bagi remaja putri. Melalui lokakarya, peserta memperoleh penguatan pengetahuan mengenai tata kelola program, strategi implementasi, pemantauan, dan pelaporan, sehingga dapat mendukung peningkatan cakupan dan kualitas pelaksanaan program suplementasi tablet tambah darah sebagai upaya pencegahan anemia dan perbaikan status gizi remaja.', 'Rp. 785.235.000', '/placeholder.jpg', 14);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Asesmen Sekolah & WASH', '2019', 'Melakukan asesmen di sekolah di Kecamatan Sulamu Kabupaten Kupang terkait layanan Pendidikan dasar dan WASH.', '', '/placeholder.jpg', 15);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Pengembangan rencana strategi program penggalangan dana dan ekonomi berkelanjutan (TAWA Semesta)', '2019 - 2020', 'Memfasilitasi dan membantu TAWA Semesta, sebuah LSM Yang berbasis di Makasar Provinsi Sulawesi Selatan untuk mengembangkan rencana strategi program penggalangan dana dan ekonomi berkelanjutan.', '', '/placeholder.jpg', 16);
INSERT INTO public.marungga_programs (title, year, description, category, image_url, order_index) VALUES ('Distribusi perlengkapan sekolah', '2019', 'Bekerja sama dengan CHARIS National Academy dan Sumba Integrated Development ( SID) mendististribusikan perlengkapan sekolah untuk 20 anak di Desa Wanggabewa Kecamatan Sumba Timur.', '', '/placeholder.jpg', 17);
